// 由 scripts/sync-models-snapshot.mjs 生成，请勿手改。
// 数据源：https://models.dev/api.json　抓取日期：2026-09-15
//
// 这是**兜底**清单：模型名输入框优先用运行时同步来的数据，拉不到时才用这份。
// 发版前跑 `npm run sync-models` 刷新，把改动一起提交。

/** 抓取日期，界面上标注「截至 X」用。 */
export const MODELS_SNAPSHOT_DATE = "2026-09-15";

/** models.dev 服务商 ID → 模型 ID（发布日期新→旧）。 */
export const MODELS_SNAPSHOT: Record<string, string[]> = {
  "kimi-for-coding": [
    "kimi-for-coding",
    "k3",
    "k3-256k",
    "kimi-for-coding-highspeed"
  ],
  "moonshotai-cn": [
    "kimi-k3",
    "kimi-k2.7-code",
    "kimi-k2.7-code-highspeed",
    "kimi-k2.6"
  ],
  "deepseek": [
    "deepseek-flash",
    "deepseek-v4-flash",
    "deepseek-v4-flash-vision-exp",
    "deepseek-v4-pro"
  ],
  "minimax-cn": [
    "MiniMax-M3",
    "MiniMax-M2.7",
    "MiniMax-M2.7-highspeed",
    "MiniMax-M2.5-highspeed",
    "MiniMax-M2.5",
    "MiniMax-M2.1",
    "MiniMax-M2"
  ],
  "minimax": [
    "MiniMax-M3",
    "MiniMax-M2.7",
    "MiniMax-M2.7-highspeed",
    "MiniMax-M2.5-highspeed",
    "MiniMax-M2.5",
    "MiniMax-M2.1",
    "MiniMax-M2"
  ],
  "alibaba-coding-plan-cn": [
    "qwen3.7-plus",
    "qwen3.7-max",
    "qwen3.6-flash",
    "qwen3.6-plus",
    "qwen3.5-plus",
    "MiniMax-M2.5",
    "glm-5",
    "qwen3-coder-next",
    "kimi-k2.5",
    "qwen3-max-2026-01-23",
    "glm-4.7",
    "qwen3-coder-plus"
  ],
  "alibaba-token-plan-cn": [
    "deepseek-v4.1-flash",
    "qwen3.8-flash",
    "deepseek-v4-pro-0813",
    "qwen3.8-max",
    "deepseek-v4-flash-0731",
    "qwen3.8-max-preview",
    "happyhorse-1.1-i2v",
    "happyhorse-1.1-r2v",
    "happyhorse-1.1-t2v",
    "glm-5.2",
    "kimi-k2.7-code",
    "qwen3.7-plus",
    "wan2.7-image",
    "wan2.7-image-pro",
    "qwen3.7-max",
    "qwen3.6-flash",
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "kimi-k2.6",
    "glm-5.1",
    "qwen3.6-plus",
    "qwen-image-2.0",
    "qwen-image-2.0-pro",
    "glm-5",
    "MiniMax-M2.5",
    "kimi-k2.5",
    "deepseek-v3.2"
  ],
  "alibaba-cn": [
    "qwen3.8-flash",
    "qwen3.8-max",
    "qwen3.7-flash",
    "glm-5.2",
    "qwen3.7-plus",
    "qwen3.7-max",
    "qwen3.6-flash",
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "kimi-k2.6",
    "qwen3.6-max-preview",
    "glm-5.1",
    "qwen3.6-plus",
    "MiniMax/MiniMax-M2.7",
    "qwen3.5-flash",
    "qwen3.5-397b-a17b",
    "qwen3.5-plus",
    "MiniMax-M2.5",
    "glm-5",
    "kimi-k2.5",
    "kimi/kimi-k2.5",
    "siliconflow/deepseek-v3.2",
    "kimi-k2-thinking",
    "siliconflow/deepseek-v3.1-terminus",
    "qwen3-max",
    "qwen3-vl-plus",
    "qwen3-omni-flash",
    "qwen3-omni-flash-realtime",
    "qwen3-asr-flash",
    "qwen3-next-80b-a3b-instruct",
    "qwen3-next-80b-a3b-thinking",
    "qwen-flash",
    "qwen3-coder-flash",
    "qwen3-coder-plus",
    "deepseek-r1-0528",
    "siliconflow/deepseek-r1-0528",
    "qwen-omni-turbo-realtime",
    "qwen3-14b",
    "qwen3-235b-a22b",
    "qwen3-32b",
    "qwen3-8b",
    "qwen3-coder-30b-a3b-instruct",
    "qwen3-coder-480b-a35b-instruct",
    "qwen3-vl-235b-a22b",
    "qwen3-vl-30b-a3b",
    "qvq-max",
    "qwq-plus",
    "qwen-long",
    "qwen-omni-turbo",
    "deepseek-r1",
    "deepseek-r1-distill-llama-70b",
    "deepseek-r1-distill-llama-8b",
    "deepseek-r1-distill-qwen-1-5b",
    "deepseek-r1-distill-qwen-14b",
    "deepseek-r1-distill-qwen-32b",
    "deepseek-r1-distill-qwen-7b",
    "deepseek-v3-1",
    "deepseek-v3-2-exp",
    "moonshot-kimi-k2-instruct",
    "qwen-mt-plus",
    "qwen-mt-turbo",
    "siliconflow/deepseek-v3-0324",
    "deepseek-v3",
    "qwen2-5-omni-7b",
    "qwq-32b",
    "qwen-turbo",
    "qwen2-5-coder-32b-instruct",
    "qwen2-5-coder-7b-instruct",
    "qwen-vl-ocr",
    "qwen-math-turbo",
    "qwen2-5-14b-instruct",
    "qwen2-5-32b-instruct",
    "qwen2-5-72b-instruct",
    "qwen2-5-7b-instruct",
    "qwen2-5-math-72b-instruct",
    "qwen2-5-math-7b-instruct",
    "qwen2-5-vl-72b-instruct",
    "qwen2-5-vl-7b-instruct",
    "qwen-math-plus",
    "qwen-vl-max",
    "qwen-max",
    "qwen-plus",
    "qwen-vl-plus",
    "qwen-deep-research",
    "qwen-doc-turbo",
    "qwen-plus-character",
    "tongyi-intent-detect-v3"
  ],
  "zhipuai": [
    "glm-5.3-flash",
    "glm-5.3",
    "glm-5.2",
    "glm-5v-turbo",
    "glm-5.1",
    "glm-5",
    "glm-4.7-flash",
    "glm-4.7-flashx",
    "glm-4.7",
    "glm-4.6v",
    "glm-4.6",
    "glm-4.5v",
    "glm-4.5",
    "glm-4.5-air",
    "glm-4.5-flash"
  ],
  "xiaomi": [
    "mimo-v2.5-pro-ultraspeed",
    "mimo-v2.5",
    "mimo-v2.5-pro",
    "mimo-v2-omni",
    "mimo-v2-pro",
    "mimo-v2-flash"
  ],
  "xiaomi-token-plan-cn": [
    "mimo-v2.5",
    "mimo-v2.5-pro",
    "mimo-v2.5-tts",
    "mimo-v2.5-tts-voiceclone",
    "mimo-v2.5-tts-voicedesign",
    "mimo-v2-pro",
    "mimo-v2-tts"
  ]
};
